### ISSUE TITLE
Clean before launching test

### ISSUE THREAD

**Issue by totojab** [totojab/owej#29]
- [x] Create repo engine (keep commits)
 - [x] Create repo redirect server (keep commits)
 - [x] Hello world to "Welcome to Sneaker Finder"
 - [x] Launch new repo on heroku
 - [x] Set ping on redirecting server
 - [ ] set access token for heroku #34
 -  [x] clean env variable in datasources.development.js

**Comment by Elrendio** [comment]
All done except #34 who's cancelled
